### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by xnacly** [xNaCly/InstagramAPIwrapper#1]
# Code Features:
- [ ] add uploading posts (from url?/from file, with caption)
- [ ] add usersettings (change profilepic/change username/other settings)
- [ ] add comments to PostObject (comments from Post to PostObject)
- [ ] add DM's (sendDM,getDMs,getDM)

# Doc Features:
- [x] add Docs
- [ ] make a video showcasing all methods

# Overtrown Features:
- [ ] add Login with Username & Password (not possible with api due to encryption)

**Comment by samuelscheit** [comment]
add support for native app api routes
